const card=document.querySelector('#app-card'),fileInput=document.querySelector('#file-input'),samples=document.querySelector('#samples');let currentFile=null,stems=null,activeAudio=null;
const icon=name=>({upload:'↑',music:'♫',file:'♪',play:'▶',pause:'Ⅱ',close:'×'})[name];
const escapeHtml=value=>{const e=document.createElement('div');e.textContent=value;return e.innerHTML};
function idle(){card.innerHTML=`<div class="upload-card"><div class="upload-icon">${icon('upload')}</div><h3>Drag your track here</h3><p>or <button data-browse>browse files</button> from your computer</p><small>MP3, WAV, FLAC or M4A · Up to 200 MB</small></div>`;samples.hidden=false}
function ready(){const size=currentFile.sample?'Fretline demo track':`${(currentFile.size/1e6).toFixed(1)} MB`;card.innerHTML=`<div class="upload-card"><div class="selected-file"><div class="file-art">${icon('file')}</div><div><strong>${escapeHtml(currentFile.name)}</strong><span>${size} · Ready to separate</span></div><button data-reset aria-label="Remove file">${icon('close')}</button></div><button class="primary process" data-start>Separate guitars <b>→</b></button><small>Creates two downloadable WAV audio files in your browser</small></div>`;samples.hidden=true}
function processing(message='Decoding your audio…',value=5){card.innerHTML=`<div class="upload-card is-processing"><div class="processing-art">${icon('music')}</div><h3>Separating guitar parts</h3><p data-message>${message}</p><div class="progress"><i style="width:${value}%"></i></div><div class="progress-row"><span data-number>${value}% complete</span><span>Working locally</span></div></div>`}
function progress(value,message){card.querySelector('.progress i').style.width=`${value}%`;card.querySelector('[data-number]').textContent=`${value}% complete`;card.querySelector('[data-message]').textContent=message}
function error(message){card.innerHTML=`<div class="upload-card"><div class="upload-icon">!</div><h3>We couldn’t read that audio</h3><p>${escapeHtml(message)}</p><button class="primary process" data-reset>Try another file</button></div>`}
function stem(name,desc,color,n){return `<article class="stem ${color}"><div class="stem-label"><span>${n}</span>${name}</div><div class="stem-visual">${'<i></i>'.repeat(9)}</div><p>${desc}</p><div class="stem-actions"><button class="round" data-play="${name}" aria-label="Preview ${name}">${icon('play')}</button><button class="download" data-download="${name}">Download WAV ↓</button></div></article>`}
function results(){card.innerHTML=`<div class="results"><div class="results-top"><div><div class="done"><b>✓</b> Separation complete</div><h3>${escapeHtml(currentFile.name)}</h3><p>Preview or download your two WAV stems.</p></div><button class="ghost" data-reset>＋ New track</button></div><div class="stem-grid">${stem('Lead guitar','Higher melodic frequencies & solos','lavender',1)}${stem('Rhythm guitar','Lower chord and riff frequencies','peach',2)}</div><div class="demo-note">This version creates real WAV stems with browser-local frequency separation. Dense mixes may need an ML inference service for cleaner instrument isolation.</div></div>`}
function choose(file){if(!file||(!file.type.startsWith('audio/')&&!file.sample))return;currentFile=file;stems=null;ready()}
function wav(buffer){const channels=buffer.numberOfChannels,frames=buffer.length,bytes=44+frames*channels*2,view=new DataView(new ArrayBuffer(bytes)),write=(offset,text)=>[...text].forEach((c,i)=>view.setUint8(offset+i,c.charCodeAt(0)));write(0,'RIFF');view.setUint32(4,bytes-8,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,bytes-44,true);let o=44;for(let i=0;i<frames;i+=1)for(let c=0;c<channels;c+=1){const s=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));view.setInt16(o,s<0?s*0x8000:s*0x7fff,true);o+=2}return new Blob([view],{type:'audio/wav'})}
async function render(buffer,kind){const ctx=new OfflineAudioContext(buffer.numberOfChannels,buffer.length,buffer.sampleRate),source=ctx.createBufferSource(),one=ctx.createBiquadFilter(),two=ctx.createBiquadFilter();source.buffer=buffer;if(kind==='lead'){one.type='highpass';one.frequency.value=900;two.type='peaking';two.frequency.value=2600;two.Q.value=.8;two.gain.value=7}else{one.type='lowpass';one.frequency.value=1400;two.type='peaking';two.frequency.value=380;two.Q.value=.7;two.gain.value=4}source.connect(one).connect(two).connect(ctx.destination);source.start();return ctx.startRendering()}
async function separate(){if(currentFile.sample){error('Demo tracks are visual samples. Upload an audio file to generate downloadable stems.');return}try{processing();const ctx=new AudioContext(),decoded=await ctx.decodeAudioData(await currentFile.arrayBuffer());await ctx.close();progress(30,'Extracting lead guitar frequencies…');const lead=await render(decoded,'lead');progress(68,'Extracting rhythm guitar frequencies…');const rhythm=await render(decoded,'rhythm');progress(90,'Encoding WAV stems…');const leadBlob=wav(lead),rhythmBlob=wav(rhythm);stems={'Lead guitar':{url:URL.createObjectURL(leadBlob)},'Rhythm guitar':{url:URL.createObjectURL(rhythmBlob)}};progress(100,'Your stems are ready.');setTimeout(results,250)}catch{error('Please upload a supported audio file (MP3, WAV, FLAC, or M4A).')}}
function play(name,button){if(!stems?.[name])return;if(activeAudio?.dataset.stem===name){activeAudio.pause();activeAudio=null;button.textContent=icon('play');return}if(activeAudio)activeAudio.pause();document.querySelectorAll('[data-play]').forEach(item=>item.textContent=icon('play'));activeAudio=new Audio(stems[name].url);activeAudio.dataset.stem=name;activeAudio.onended=()=>{button.textContent=icon('play');activeAudio=null};activeAudio.play();button.textContent=icon('pause')}
function download(name){const link=document.createElement('a');link.href=stems[name].url;link.download=`${currentFile.name.replace(/\.[^/.]+$/,'')}-${name.toLowerCase().replace(' ','-')}.wav`;link.click()}
document.addEventListener('click',event=>{if(event.target.closest('[data-browse]'))fileInput.click();if(event.target.closest('[data-reset]')){if(activeAudio)activeAudio.pause();currentFile=null;stems=null;idle()}if(event.target.closest('[data-start]'))separate();const p=event.target.closest('[data-play]');if(p)play(p.dataset.play,p);const d=event.target.closest('[data-download]');if(d)download(d.dataset.download);const s=event.target.closest('[data-sample]');if(s)choose({name:`${s.dataset.sample.toLowerCase().replaceAll(' ','-')}.mp3`,sample:true})});fileInput.addEventListener('change',()=>choose(fileInput.files[0]));card.addEventListener('dragover',event=>event.preventDefault());card.addEventListener('drop',event=>{event.preventDefault();choose(event.dataTransfer.files[0])});idle();
